# Generated by Django 4.1.5 on 2023-01-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_student_mail_alter_student_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
