# Generated by Django 4.1.5 on 2023-02-01 09:35

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_student_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mail',
            field=models.EmailField(max_length=254, unique=True, validators=[app1.models.validate_email]),
        ),
    ]
